numServers: 3
numClients: 1

debug: true

persist: true

clientRequestTimeout: 2000ms

fd:
  pullInterval: 500ms
  timeout: 500ms

mailboxes:
  receiveChanSize: 10000
  dialTimeout: 500ms
  readTimeout: 500ms
  writeTimeout: 500ms

leaderElection:
  timeout: 1s
  timeoutOffset: 1s

appendEntriesSendInterval: 50ms

sharedResourceTimeout: 2ms

inputChanReadTimeout: 2ms

servers:
  1:
    mailboxAddr: "server1:8000"
    monitorAddr: "server1:9000"
  
  2:
    mailboxAddr: "server2:8000"
    monitorAddr: "server2:9000"
    
  3:
    mailboxAddr: "server3:8000"
    monitorAddr: "server3:9000"

clients:
  1:
    mailboxAddr: "client1:8000"
