services:
  server1: &srv
    image: raftkvs-server:antithesis
    container_name: server1
    hostname: server1
    environment:
      - PGO_TRACE_DIR=/workspaces/antithesis/traces_found
    volumes:
      - logs-volume:/workspaces/antithesis/traces_found
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 1
  server2:
    <<: *srv
    container_name: server2
    hostname: server2
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 2
  server3:
    <<: *srv
    container_name: server3
    hostname: server3
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 3
  # server4:
  #   <<: *srv
  #   container_name: server4
  #   hostname: server4
  #   command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 4
  # server5:
  #   <<: *srv
  #   container_name: server5
  #   hostname: server5
  #   command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 5
  client1:
    <<: *srv
    image: raftkvs-client:antithesis
    container_name: client1
    hostname: client1
    command: /workspaces/antithesis/pretend_to_run.sh

volumes:
  logs-volume:
