name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '21']
        golang-version: ['1.22', '1.23']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.golang-version }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - name: 'Run tests'
      run: ./mill pgo.test
