name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '21']
        golang-version: ['1.22', '1.23']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.golang-version }}
    - uses: VirtusLab/scala-cli-setup@main
      with:
        jvm: ${{ matrix.java-version }}
    - name: 'Setup TLA+ Tools'
      run: scala-cli run . --main-class setup_sc
    - name: 'Run tests'
      run: scala-cli test . -- -l org.scalatest.tags.Slow
    - name: 'Upload Fuzz Test Results on Test Failure (in case there are some)'
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-test-results
        path: fuzz_output/*
