services:
  server1:
    image: raftkvs-server:antithesis
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 1
  server2:
    image: raftkvs-server:antithesis
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 2
  server3:
    image: raftkvs-server:antithesis
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 3
  server4:
    image: raftkvs-server:antithesis
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 4
  server5:
    image: raftkvs-server:antithesis
    command: /workspaces/antithesis/raftkvs-server -c /workspaces/antithesis/config.yaml -srvId 5
  client1:
    image: raftkvs-client:antithesis
    command: /workspaces/antithesis/pretend_to_run.sh
